import { describe, expect, it } from "vitest";
import { CompetitionEngine } from "../application/competition-engine.js";
import { ParticipantEngine, ScheduleEngine, SeededMatchSimulator, StandingEngine } from "../application/engines.js";
import { FixtureStatus, ParticipantSourceType, StageType, StandingMetric, type CompetitionStage } from "../domain/types.js";
import { MemoryCompetitionRepository, MemoryFixtureRepository, MemoryParticipantRepository, MemorySeasonRepository, MemoryStageRepository, MemoryStandingRepository } from "../infrastructure/memory-repositories.js";

const stage: CompetitionStage = { id: "stage", seasonId: "122", name: "Liga", order: 1, type: StageType.LEAGUE, participantRule: { source: ParticipantSourceType.ALL_TEAMS }, leagueFormat: { legs: 2, points: { win: 3, draw: 1, loss: 0 }, tieBreakers: [StandingMetric.POINTS, StandingMetric.WINS, StandingMetric.GOAL_DIFFERENCE, StandingMetric.GOALS_FOR] } };
const teams = Array.from({ length: 20 }, (_, index) => ({ id: String(index + 1), name: `Team ${index + 1}` }));
function setup() { const participants = new MemoryParticipantRepository(new Map([["122", teams]])); const fixtures = new MemoryFixtureRepository(); const standings = new MemoryStandingRepository(); return { engine: new CompetitionEngine({ competitions: new MemoryCompetitionRepository([{ id: "8", name: "Brasileirão", type: "league" }]), seasons: new MemorySeasonRepository([{ id: "122", competitionId: "8", year: 2026, numberOfCompetitors: 20 }]), stages: new MemoryStageRepository([stage]), participants, fixtures, standings, participantEngine: new ParticipantEngine(), scheduleEngine: new ScheduleEngine(), standingEngine: new StandingEngine(), simulator: new SeededMatchSimulator(42) }), participants, fixtures, standings }; }
describe("competition engine", () => {
  it("resolves all season teams and produces a 38-round, 380-fixture double round robin", async () => { const { engine, participants, fixtures } = setup(); const season = await engine.loadSeason("8", "122"); await engine.initialize(season); await engine.generateSchedule(season.id); expect(await participants.findByStageId("stage")).toHaveLength(20); const rounds = await fixtures.findRoundsByStageId("stage"); const scheduled = await fixtures.findFixturesByStageId("stage"); expect(rounds).toHaveLength(38); expect(scheduled).toHaveLength(380); expect(new Set(scheduled.map((f) => `${f.homeTeamId}-${f.awayTeamId}`)).size).toBe(380); expect(scheduled.every((f) => f.homeTeamId !== f.awayTeamId)).toBe(true); });
  it("applies the next round and updates the standings", async () => { const { engine, standings } = setup(); const season = await engine.loadSeason("8", "122"); await engine.initialize(season); await engine.generateSchedule(season.id); const played = await engine.playNextRound("stage"); expect(played).toHaveLength(10); expect(played.every((f) => f.status === FixtureStatus.FINISHED)).toBe(true); const table = await standings.findByStageId("stage"); expect(table).toHaveLength(20); expect(table.reduce((sum, entry) => sum + entry.played, 0)).toBe(20); expect(table[0].position).toBe(1); });
  it("calculates win, draw, goals and goal difference", () => { const engine = new StandingEngine(); const entries = engine.calculate(stage, [{ id: "x", stageId: "stage", roundId: "r", homeTeamId: "1", awayTeamId: "2", status: FixtureStatus.FINISHED, legs: [{ number: 1, homeTeamId: "1", awayTeamId: "2", result: { homeGoals: 2, awayGoals: 0 } }] }, { id: "y", stageId: "stage", roundId: "r", homeTeamId: "2", awayTeamId: "3", status: FixtureStatus.FINISHED, legs: [{ number: 1, homeTeamId: "2", awayTeamId: "3", result: { homeGoals: 1, awayGoals: 1 } }] }], ["1", "2", "3"]); expect(entries.find((e) => e.teamId === "1")).toMatchObject({ points: 3, wins: 1, goalsFor: 2, goalsAgainst: 0, goalDifference: 2 }); expect(entries.find((e) => e.teamId === "2")).toMatchObject({ points: 1, draws: 1, losses: 1, goalsFor: 1, goalsAgainst: 3, goalDifference: -2 }); });
});
