export const DEFAULT_CLIMATES = [
  "Tropical", "Dry", "Temperate", "Continental", "Polar", "Mediterranean", "Subtropical",
  "Oceanic", "Humid Subtropical", "Monsoon", "Savanna", "Steppe", "Desert", "Subarctic", "Tundra", "Alpine",
] as const;

export const DEFAULT_REFERENCE_LISTS = {
  genders: ["Male", "Female"],
  weekdays: [
    ["Monday", 1, 0], ["Tuesday", 2, 0], ["Wednesday", 3, 0], ["Thursday", 4, 0],
    ["Friday", 5, 0], ["Saturday", 6, 1], ["Sunday", 7, 1],
  ],
  nationalityMethods: ["Birth", "Descent", "Naturalization", "Marriage"],
  developmentStates: ["Developed", "Emerging", "Developing"],
  clubStatuses: ["Active", "Reserve", "Inactive"],
  competitionTypes: ["League", "Cup", "Tournament"],
  competitionStageTypes: ["League", "Group", "Knockout"],
  pitchTypes: [
    "Natural Grass", "Artificial Turf", "Hybrid", "Soft Artificial Turf", "Hard Artificial Turf", "Gravel and Dirt",
    "Gravel", "Dirt", "Sand", "Hybrid Grass",
  ],
  stadiumOwnerTypes: ["Club", "Municipal", "Private", "National", "Council", "Chairman", "Supporters"],
  grassDeteriorationRates: [["Slow", 1], ["Medium", 2], ["Fast", 3]],
  qualityStates: [["Very Poor", 1], ["Poor", 2], ["Acceptable", 3], ["Good", 4], ["Very Good", 5]],
  environmentQualities: [["Basic", 1], ["Standard", 2], ["High Level", 3], ["State of the Art", 4]],
  personTypes: ["PLAYER", "STAFF", "OFFICIAL", "AGENT", "NON_PLAYER", "RETIRED", "JOURNALIST"],
  positions: [
    "Goalkeeper", "Defender", "Centre-Back", "Left-Back", "Right-Back", "Defensive Midfielder",
    "Central Midfielder", "Attacking Midfielder", "Left Winger", "Right Winger", "Striker",
    "Left Back", "Centre Back", "Right Back", "Right Wing-Back", "Left Wing-Back", "Left Midfielder",
    "Right Midfielder",
  ],
  refereeCategories: ["International", "Professional", "National", "Regional"],
  employments: ["Manager", "Assistant Manager", "Coach", "Goalkeeping Coach", "Fitness Coach", "Scout", "Physiotherapist", "Doctor", "Analyst", "Director", "Chief Executive", "Chairperson"],
  weatherSeasons: ["Spring", "Summer", "Autumn", "Winter"],
  secondNationalityInfo: [
    "No Data", "Born in Country", "Family Born in Country", "Eligible for Country",
    "Not Eligible for Country", "Previously Played for Country", "Citizenship by Descent",
    "Naturalized but Not Eligible", "Naturalized but Still Foreign", "Declared for National Team",
    "Citizenship by Descent but Not Yet Eligible",
  ],
  moneyDirections: ["Income", "Expense"],
  paymentIntervals: [["Daily", 1, 0, 0], ["Weekly", 7, 0, 0], ["Monthly", 0, 1, 0], ["Quarterly", 0, 3, 0], ["Semiannual", 0, 6, 0], ["Annual", 0, 0, 1]],
  clauseConditions: ["After International Appearances", "League Appearances", "League Goals", "Per League Appearance", "Per League Goal"],
  suspensionTypes: ["League", "Cup", "National", "Continental", "International", "International Including Friendlies"],
  suspensions: ["Global", "League", "Continental", "National", "Cup", "Sabbatical", "Holiday", "Military Leave", "Study Leave"],
  gameLocationTypes: ["All Matches", "Away Matches", "Home Matches"],
  injuryClassifications: ["Internal", "Foot", "Knee", "Thigh", "Groin", "Torso", "Hand", "Arm", "Shoulder", "Head", "Rehabilitation"],
  injuryReasons: ["Impact with Player", "Impact from Fall", "Weightlifting", "Turning", "Sprint", "Jumping", "Overuse", "Kicking Ball", "Catching Ball", "Saving", "Tackle", "Violent Conduct"],
  ownershipTypes: [["Private", 0], ["Member-Owned", 1], ["Public", 1], ["Municipal", 0], ["National", 0]],
  ownershipPromises: ["Improve Youth Development", "Improve Training Facilities", "Improve Stadium", "Increase Transfer Budget", "Reduce Debt"],
  presidentTitles: ["President", "Chairman", "Owner"],
  patronTypes: ["No Patron", "Local Patron", "Business Consortium", "Supporters Trust"],
  embargoTypes: ["Transfer Ban", "Registration Ban", "Wage Restriction", "Spending Limit"],
  revenueTypes: ["Broadcasting", "Ticket Sales", "Sponsorship", "Merchandising", "Prize Money", "Other"],
  debtSources: ["Bank Loan", "Owner Loan", "Government Loan", "Bond", "Other"],
  equipmentTypes: ["Home", "Away", "Third", "Special", "Goalkeeper Home", "Goalkeeper Away", "Goalkeeper Third", "Goalkeeper Special"],
  equipmentPieces: ["Shirt", "Text", "Shorts", "Socks"],
  equipmentStyles: ["Plain", "Vertical Stripes", "Horizontal Stripes", "Hoops", "Diagonal Sash", "Halves", "Quarters", "Gradient"],
  objectiveTypes: ["Become Most Respected in Country", "Become Most Respected in Continent", "Become Most Respected in World", "Sign Players of a Nationality", "Sign Renowned Players", "Play Attacking Football", "Play Defensive Football", "Play Possession Football", "Play Direct Football", "Excel at Set Pieces", "Play Attractive Football", "Play Counter-Attacking Football", "Play High-Intensity Football", "Develop Youth Players"],
  retiredNumberReasons: ["In Memoriam", "Club Legend", "Supporter", "Famous Player"],
  affiliationTypes: ["Partner Club", "Reserve Team", "Satellite Club", "B Team", "C Team", "Good Relations", "Friendly Partner", "Shared Academy", "Regional Academy"],
  transferStatuses: ["Planned", "Negotiating", "Confirmed", "Completed", "Cancelled"],
  transferTypes: ["Permanent", "Loan", "Free Transfer", "Youth Transfer"],
  contractTypes: ["Professional", "Part-Time", "Youth", "Amateur", "Non-Playing Staff"],
  contractClauseTypes: ["Release Clause", "Sell-On Percentage", "Appearance Bonus", "Goal Bonus", "Promotion Bonus", "Relegation Wage Reduction"],
  playerAchievementTypes: ["Winner", "Runner-Up", "Third Place", "Fourth Place", "Relegated", "Professional Debut", "Promoted", "Individual Award"],
  pressPeriods: ["Any Time", "Daily", "Weekday Morning", "Sunday", "Friday", "Weekly", "Quarterly"],
  newsReaches: ["Local", "Regional", "National", "Continental", "Global", "Competition", "Club"],
  pressTypes: ["Newspaper", "Television", "Radio", "Online", "Magazine", "Wire Service"],
  awardPeriods: ["Match", "Month", "Season", "Calendar Year", "Career"],
  awardRecipientTypes: ["Player", "Team", "Club", "Manager", "Staff", "Nation"],
  awardTypes: ["Best Player", "Best Young Player", "Best Goalkeeper", "Best Manager", "Team of the Year", "Top Scorer"],
  awardVotingTypes: ["Media Vote", "Player Vote", "Coach Vote", "Public Vote", "Statistical"],
  awardOrganizers: ["League", "Federation", "Players Association", "Media"],
  awardStatistics: ["Appearances", "Goals", "Assists", "Clean Sheets", "Average Rating"],
  recordTypes: ["Biggest Win", "Biggest Defeat", "Highest Scoring Match", "Highest Attendance", "Most Consecutive Wins", "Most Consecutive Matches Unbeaten", "Most Appearances", "Most Goals", "Youngest Player", "Oldest Player", "Highest Transfer Fee"],
  trophyTypes: ["League Trophy", "Cup Trophy", "Super Cup Trophy"],
  roleDuties: ["Defend", "Support", "Attack"],
} as const;

export const DEFAULT_INJURY_SUBCLASSIFICATIONS: ReadonlyArray<readonly [string, readonly string[]]> = [
  ["Internal", ["General"]],
  ["Foot", ["Foot", "Heel", "Toe", "Achilles Tendon", "Ankle"]],
  ["Knee", ["Knee", "Collateral Ligament", "Cruciate Ligament", "Joint"]],
  ["Thigh", ["Thigh", "Hamstring", "Quadriceps", "Femur", "Upper Leg"]],
  ["Groin", ["Adductor", "Hip", "Pelvis"]],
  ["Torso", ["Rib", "Spine", "Back", "Chest", "General"]],
  ["Hand", ["Wrist", "Hand", "Finger"]],
  ["Arm", ["Radius", "Elbow", "Humerus", "Arm"]],
  ["Shoulder", ["Shoulder"]],
  ["Head", ["Brain", "Head", "Face", "Jaw", "Skull", "Nose", "Neck"]],
  ["Rehabilitation", ["General", "Illness"]],
];

export const DEFAULT_PLAYER_ROLES: ReadonlyArray<readonly [string, readonly string[]]> = [
  ["Striker", ["Deep-Lying Forward", "Centre Forward", "Target Forward", "Poacher", "Channel Forward", "False Nine", "Tracking Centre Forward", "Central Outlet Centre Forward", "Second Striker", "Splitting Outlet Centre Forward"]],
  ["Left Winger", ["Winger", "Inside Forward", "Playmaking Winger", "Wide Forward", "Inside Winger", "Tracking Winger", "Inside Outlet Winger", "Wide Outlet Winger"]],
  ["Right Winger", ["Winger", "Inside Forward", "Playmaking Winger", "Wide Forward", "Inside Winger", "Tracking Winger", "Inside Outlet Winger", "Wide Outlet Winger"]],
  ["Attacking Midfielder", ["Attacking Midfielder", "Advanced Playmaker", "Free Role", "Channel Midfielder", "Tracking Attacking Midfielder", "Central Outlet Attacking Midfielder", "Splitting Outlet Attacking Midfielder"]],
  ["Left Midfielder", ["Wide Midfielder", "Tracking Wide Midfielder", "Wide Outlet Wide Midfielder"]],
  ["Right Midfielder", ["Wide Midfielder", "Tracking Wide Midfielder", "Wide Outlet Wide Midfielder"]],
  ["Central Midfielder", ["Central Midfielder", "Wide Central Midfielder", "Midfield Playmaker", "Pressing Central Midfielder", "Screening Central Midfielder", "Wide Covering Central Midfielder", "Box-To-Box Midfielder"]],
  ["Defensive Midfielder", ["Defensive Midfielder", "Deep-Lying Playmaker", "Box-To-Box Midfielder", "Half Back", "Box-To-Box Playmaker", "Dropping Defensive Midfielder", "Screening Defensive Midfielder", "Wide Covering Defensive Midfielder"]],
  ["Left Back", ["Full Back", "Inside Full-Back", "Playmaking Full-Back", "Pressing Full-Back", "Holding Full-Back"]],
  ["Right Back", ["Full Back", "Inside Full-Back", "Playmaking Full-Back", "Pressing Full-Back", "Holding Full-Back"]],
  ["Left Wing-Back", ["Wing Back", "Advanced Wing-Back", "Inside Wing-Back", "Playmaking Wing-Back", "Pressing Wing-Back", "Holding Wing-Back"]],
  ["Right Wing-Back", ["Wing Back", "Advanced Wing-Back", "Inside Wing-Back", "Playmaking Wing-Back", "Pressing Wing-Back", "Holding Wing-Back"]],
  ["Centre Back", ["Centre-Back", "Advanced Centre-Back", "Ball-Playing Centre-Back", "No-Nonsense Centre-Back", "Stopping Centre-Back", "Covering Centre-Back"]],
  ["Goalkeeper", ["No-Nonsense Goalkeeper", "Ball-Playing Goalkeeper", "Goalkeeper", "Sweeper Keeper", "Line-Holding Keeper"]],
];

