export const CONTINENTS = [
  ["Africa", "AF"],
  ["Asia", "AS"],
  ["Europe", "EU"],
  ["North America", "NA"],
  ["South America", "SA"],
  ["Oceania", "OC"],
] as const;

export const REGIONS = [
  ["South America", "SA", "South America"],
  ["North America", "NA", "North America"],
  ["Central America", "CA", "North America"],
  ["Caribbean", "CAR", "North America"],
  ["Western Europe", "WE", "Europe"],
  ["Eastern Europe", "EE", "Europe"],
  ["Northern Europe", "NE", "Europe"],
  ["Southern Europe", "SE", "Europe"],
  ["Middle East", "ME", "Asia"],
  ["Central Asia", "CA", "Asia"],
  ["East Asia", "EA", "Asia"],
  ["South Asia", "SA", "Asia"],
  ["Southeast Asia", "SEA", "Asia"],
  ["North Asia", "NA", "Asia"],
  ["Northern Africa", "NAF", "Africa"],
  ["Western Africa", "WAF", "Africa"],
  ["Central Africa", "CAF", "Africa"],
  ["Eastern Africa", "EAF", "Africa"],
  ["Southern Africa", "SAF", "Africa"],
  ["Melanesia", "MEL", "Oceania"],
  ["Micronesia", "MIC", "Oceania"],
  ["Polynesia", "POL", "Oceania"],
] as const;

export const NATIONS: Array<[string, string, string]> = [
  ["Argentina", "ARG", "South America"],
  ["Bolivia", "BOL", "South America"],
  ["Brazil", "BRA", "South America"],
  ["Chile", "CHI", "South America"],
  ["Colombia", "COL", "South America"],
  ["Ecuador", "ECU", "South America"],
  ["Guyana", "GUY", "South America"],
  ["Paraguay", "PAR", "South America"],
  ["Peru", "PER", "South America"],
  ["Suriname", "SUR", "South America"],
  ["Uruguay", "URU", "South America"],
  ["Venezuela", "VEN", "South America"],
  ["Canada", "CAN", "North America"],
  ["United States", "USA", "North America"],
  ["Mexico", "MEX", "North America"],
  ["Costa Rica", "CRC", "Central America"],
  ["El Salvador", "SLV", "Central America"],
  ["Guatemala", "GUA", "Central America"],
  ["Honduras", "HON", "Central America"],
  ["Nicaragua", "NCA", "Central America"],
  ["Panama", "PAN", "Central America"],
  ["Belize", "BLZ", "Central America"],
  ["Cuba", "CUB", "Caribbean"],
  ["Haiti", "HAI", "Caribbean"],
  ["Dominican Republic", "DOM", "Caribbean"],
  ["Jamaica", "JAM", "Caribbean"],
  ["Trinidad and Tobago", "TRI", "Caribbean"],
  ["England", "ENG", "Northern Europe"],
  ["Scotland", "SCO", "Northern Europe"],
  ["Wales", "WAL", "Northern Europe"],
  ["Northern Ireland", "NIR", "Northern Europe"],
  ["France", "FRA", "Western Europe"],
  ["Germany", "GER", "Western Europe"],
  ["Netherlands", "NED", "Western Europe"],
  ["Belgium", "BEL", "Western Europe"],
  ["Spain", "ESP", "Southern Europe"],
  ["Portugal", "POR", "Southern Europe"],
  ["Italy", "ITA", "Southern Europe"],
  ["Greece", "GRE", "Southern Europe"],
  ["Switzerland", "SUI", "Western Europe"],
  ["Austria", "AUT", "Western Europe"],
  ["Poland", "POL", "Eastern Europe"],
  ["Czech Republic", "CZE", "Eastern Europe"],
  ["Slovakia", "SVK", "Eastern Europe"],
  ["Hungary", "HUN", "Eastern Europe"],
  ["Romania", "ROU", "Eastern Europe"],
  ["Bulgaria", "BUL", "Eastern Europe"],
  ["Croatia", "CRO", "Southern Europe"],
  ["Serbia", "SRB", "Southern Europe"],
  ["Ukraine", "UKR", "Eastern Europe"],
  ["Russia", "RUS", "North Asia"],
  ["Turkey", "TUR", "Middle East"],
  ["Israel", "ISR", "Middle East"],
  ["Saudi Arabia", "KSA", "Middle East"],
  ["Iran", "IRN", "Middle East"],
  ["Iraq", "IRQ", "Middle East"],
  ["Japan", "JPN", "East Asia"],
  ["South Korea", "KOR", "East Asia"],
  ["China", "CHN", "East Asia"],
  ["India", "IND", "South Asia"],
  ["Pakistan", "PAK", "South Asia"],
  ["Bangladesh", "BAN", "South Asia"],
  ["Thailand", "THA", "Southeast Asia"],
  ["Vietnam", "VIE", "Southeast Asia"],
  ["Indonesia", "IDN", "Southeast Asia"],
  ["Malaysia", "MAS", "Southeast Asia"],
  ["Singapore", "SIN", "Southeast Asia"],
  ["Philippines", "PHI", "Southeast Asia"],
  ["Australia", "AUS", "Oceania"],
  ["New Zealand", "NZL", "Oceania"],
  ["Papua New Guinea", "PNG", "Melanesia"],
  ["Fiji", "FIJ", "Melanesia"],
  ["Samoa", "SAM", "Polynesia"],
  ["Tonga", "TGA", "Polynesia"],
  ["Egypt", "EGY", "Northern Africa"],
  ["Morocco", "MAR", "Northern Africa"],
  ["Algeria", "ALG", "Northern Africa"],
  ["Tunisia", "TUN", "Northern Africa"],
  ["Nigeria", "NGA", "Western Africa"],
  ["Ghana", "GHA", "Western Africa"],
  ["Senegal", "SEN", "Western Africa"],
  ["Ivory Coast", "CIV", "Western Africa"],
  ["Cameroon", "CMR", "Central Africa"],
  ["Democratic Republic of the Congo", "COD", "Central Africa"],
  ["Kenya", "KEN", "Eastern Africa"],
  ["Tanzania", "TAN", "Eastern Africa"],
  ["Ethiopia", "ETH", "Eastern Africa"],
  ["South Africa", "RSA", "Southern Africa"],
  ["Zimbabwe", "ZIM", "Southern Africa"],
];

export const CONFEDERATIONS = [
  ["AFC", "Asian Football Confederation"],
  ["CAF", "Confederation of African Football"],
  ["CONCACAF", "Confederation of North, Central America and Caribbean Association Football"],
  ["CONMEBOL", "South American Football Confederation"],
  ["OFC", "Oceania Football Confederation"],
  ["UEFA", "Union of European Football Associations"],
] as const;

export const CONFEDERATION_MEMBERS: Record<string, string[]> = {
  CONMEBOL: ["Argentina", "Bolivia", "Brazil", "Chile", "Colombia", "Ecuador", "Guyana", "Paraguay", "Peru", "Suriname", "Uruguay", "Venezuela"],
  CONCACAF: ["Canada", "United States", "Mexico", "Costa Rica", "El Salvador", "Guatemala", "Honduras", "Nicaragua", "Panama", "Belize", "Cuba", "Haiti", "Dominican Republic", "Jamaica", "Trinidad and Tobago"],
  UEFA: ["England", "Scotland", "Wales", "Northern Ireland", "France", "Germany", "Netherlands", "Belgium", "Spain", "Portugal", "Italy", "Greece", "Switzerland", "Austria", "Poland", "Czech Republic", "Slovakia", "Hungary", "Romania", "Bulgaria", "Croatia", "Serbia", "Ukraine", "Russia", "Turkey", "Israel"],
  AFC: ["Saudi Arabia", "Iran", "Iraq", "Japan", "South Korea", "China", "India", "Pakistan", "Bangladesh", "Thailand", "Vietnam", "Indonesia", "Malaysia", "Singapore", "Philippines"],
  CAF: ["Egypt", "Morocco", "Algeria", "Tunisia", "Nigeria", "Ghana", "Senegal", "Ivory Coast", "Cameroon", "Democratic Republic of the Congo", "Kenya", "Tanzania", "Ethiopia", "South Africa", "Zimbabwe"],
  OFC: ["Australia", "New Zealand", "Papua New Guinea", "Fiji", "Samoa", "Tonga"],
};

export const CURRENCIES = [
  ["Brazilian Real", "BRL"],
  ["Argentine Peso", "ARS"],
  ["Bolivian Boliviano", "BOB"],
  ["Chilean Peso", "CLP"],
  ["Colombian Peso", "COP"],
  ["Peruvian Sol", "PEN"],
  ["Uruguayan Peso", "UYU"],
  ["US Dollar", "USD"],
  ["Canadian Dollar", "CAD"],
  ["Mexican Peso", "MXN"],
  ["Euro", "EUR"],
  ["British Pound", "GBP"],
  ["Swiss Franc", "CHF"],
  ["Polish Zloty", "PLN"],
  ["Japanese Yen", "JPY"],
  ["Chinese Yuan", "CNY"],
  ["Indian Rupee", "INR"],
  ["Australian Dollar", "AUD"],
  ["New Zealand Dollar", "NZD"],
] as const;

export const LANGUAGES = [
  ["English", "Indo-European", "Germanic", "West Germanic"],
  ["Spanish", "Indo-European", "Italic", "Romance"],
  ["Portuguese", "Indo-European", "Italic", "Romance"],
  ["French", "Indo-European", "Italic", "Romance"],
  ["Italian", "Indo-European", "Italic", "Romance"],
  ["German", "Indo-European", "Germanic", "West Germanic"],
  ["Dutch", "Indo-European", "Germanic", "West Germanic"],
  ["Polish", "Indo-European", "Balto-Slavic", "West Slavic"],
  ["Russian", "Indo-European", "Balto-Slavic", "East Slavic"],
  ["Arabic", "Afro-Asiatic", "Semitic", "Central Semitic"],
  ["Persian", "Indo-European", "Indo-Iranian", "Iranian"],
  ["Turkish", "Turkic", "Common Turkic", "Oghuz"],
  ["Japanese", "Japonic", "Japanese", "Eastern Japonic"],
  ["Korean", "Koreanic", "Korean", "Korean"],
  ["Mandarin Chinese", "Sino-Tibetan", "Sinitic", "Chinese"],
  ["Hindi", "Indo-European", "Indo-Iranian", "Indo-Aryan"],
] as const;




