import { LEAGUE_MATCHES_PER_ROUND, LEAGUE_TEAM_COUNT, LEAGUE_TOTAL_MATCHES, LEAGUE_TOTAL_ROUNDS } from "../../../rules/league";
import type { CompetitionStage, StageFormat } from "../../../types";
import { NumberInput, SelectField, Stat, Toggle } from "../../editor/shared";

export function FormatPanel({ stage, onChange }: {
  stage: CompetitionStage;
  onChange: (id: number, patch: Partial<CompetitionStage["formatRule"]>) => void;
}) {
  const format = stage.formatRule.formatType;

  return (
    <div className="space-y-5">
      <div className="grid gap-4 md:grid-cols-4">
        <SelectField
          label="Format"
          value={format}
          options={["LEAGUE", "GROUP", "KNOCKOUT"]}
          onChange={value => onChange(stage.id, { formatType: value as StageFormat })}
        />
        <NumberInput label="Participants" value={stage.formatRule.participantCount} onChange={value => onChange(stage.id, { participantCount: value ?? 2 })} />
        <NumberInput label="Legs" value={stage.formatRule.legs} onChange={value => onChange(stage.id, { legs: Math.max(1, Math.min(4, value ?? 1)) })} />
        <Toggle label="Home / Away" value={stage.formatRule.homeAway === 1} onChange={value => onChange(stage.id, { homeAway: value ? 1 : 0 })} />
      </div>

      {format === "GROUP" && (
        <div className="grid gap-4 md:grid-cols-2">
          <NumberInput label="Group Count" value={stage.formatRule.groupCount} onChange={value => onChange(stage.id, { groupCount: value ?? 1 })} />
          <NumberInput label="Teams / Group" value={stage.formatRule.participantsPerGroup} onChange={value => onChange(stage.id, { participantsPerGroup: value ?? 1 })} />
        </div>
      )}

      <div className="grid gap-4 md:grid-cols-3">
        <Toggle label="Aggregate Score" value={stage.formatRule.aggregateScore === 1} onChange={value => onChange(stage.id, { aggregateScore: value ? 1 : 0 })} />
        <Toggle label="Extra Time" value={stage.formatRule.extraTime === 1} onChange={value => onChange(stage.id, { extraTime: value ? 1 : 0 })} />
        <Toggle label="Penalties" value={stage.formatRule.penalties === 1} onChange={value => onChange(stage.id, { penalties: value ? 1 : 0 })} />
        <Toggle label="Away Goals Rule" value={stage.formatRule.awayGoalsRule === 1} onChange={value => onChange(stage.id, { awayGoalsRule: value ? 1 : 0 })} />
      </div>

      {format === "LEAGUE" && (
        <div className="rounded-xl border border-white/10 bg-white/[0.02] p-4 text-xs text-slate-500">
          A 20-team double round robin produces {LEAGUE_TOTAL_ROUNDS} rounds, {LEAGUE_MATCHES_PER_ROUND} matches per round and {LEAGUE_TOTAL_MATCHES} matches in total.
        </div>
      )}

      {format === "KNOCKOUT" && (
        <div className="rounded-xl border border-amber-400/10 bg-amber-400/[0.03] p-4 text-xs text-amber-200/70">
          Knockout stages use the aggregate/extra-time/penalty rules above. A future stage can consume their qualified winners.
        </div>
      )}

      {format === "GROUP" && (
        <div className="rounded-xl border border-sky-400/10 bg-sky-400/[0.03] p-4 text-xs text-sky-200/70">
          Group placement is generated by the configured draw and can feed later stages through participant sources.
        </div>
      )}
    </div>
  );
}