import { FixtureStatus, StandingMetric, type CompetitionStage, type Fixture, type StandingEntry } from "../../database/types.js";

export class StandingEngine {
  calculate(stage: CompetitionStage, fixtures: Fixture[], teamIds: string[]): StandingEntry[] {
    if (!stage.leagueFormat) throw new Error("Standing calculation requires league format");
    const entries = new Map(teamIds.map((teamId) => [teamId, { stageId: stage.id, teamId, played: 0, points: 0, wins: 0, draws: 0, losses: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, position: 0 }]));
    for (const fixture of fixtures) { const score = fixture.legs[0]?.result; if (fixture.status !== FixtureStatus.FINISHED || !score) continue; const home = entries.get(fixture.homeTeamId); const away = entries.get(fixture.awayTeamId); if (!home || !away) throw new Error("Fixture team is not a stage participant"); home.played++; away.played++; home.goalsFor += score.homeGoals; home.goalsAgainst += score.awayGoals; away.goalsFor += score.awayGoals; away.goalsAgainst += score.homeGoals; if (score.homeGoals > score.awayGoals) { home.wins++; home.points += stage.leagueFormat.points.win; away.losses++; away.points += stage.leagueFormat.points.loss; } else if (score.homeGoals < score.awayGoals) { away.wins++; away.points += stage.leagueFormat.points.win; home.losses++; home.points += stage.leagueFormat.points.loss; } else { home.draws++; away.draws++; home.points += stage.leagueFormat.points.draw; away.points += stage.leagueFormat.points.draw; } }
    const metric = (entry: StandingEntry, rule: StandingMetric) => rule === StandingMetric.POINTS ? entry.points : rule === StandingMetric.WINS ? entry.wins : rule === StandingMetric.GOAL_DIFFERENCE ? entry.goalDifference : rule === StandingMetric.GOALS_FOR ? entry.goalsFor : 0;
    const result = [...entries.values()].map((entry) => ({ ...entry, goalDifference: entry.goalsFor - entry.goalsAgainst })); result.sort((a, b) => { for (const rule of stage.leagueFormat!.tieBreakers) { const difference = metric(b, rule) - metric(a, rule); if (difference) return difference; } return a.teamId.localeCompare(b.teamId); }); return result.map((entry, index) => ({ ...entry, position: index + 1 }));
  }
}
