export type EditorRoute =
  | "dashboard"
  | "geography"
  | "continents"
  | "countries"
  | "regions"
  | "cities"
  | "languages"
  | "climates"
  | "people"
  | "players"
  | "clubs"
  | "stadiums"
  | "competitions"
  | "fast-start"
  | "validation"
  | "export";